### ISSUE TITLE
doc request: Note supported capes on MachineKit page

### ISSUE THREAD

**Issue by brandonheller** [cdsteinkuehler/MachineKit#6]
I'm not sure what's been tested here.  If you want me to directly make changes to the page for minor stuff like this instead, let me know.

**Comment by cdsteinkuehler** [comment]
Feel free to directly make changes like this.  That's why I added you as a blog author, rather than just copying your post onto the blog.  At the moment, the only cape known to work is the BeBoPr.  The K9 _should_ work but I don't have one to test with (yet) and they're not generally available.  I'm hoping someone works on getting a Replicape and maybe I'll get time to make the CapeR (RAMPS to Cape interface) board I have planned.

**Comment by brandonheller** [comment]
I would do that, but I don't actually have permissions to modify pages or posts; I can only add new ones.  Can you check my permissions if you'd prefer direct edits (which I'd also prefer, of course - a little trust saves a lot of wasted time).

**Comment by brandonheller** [comment]
Fixed.
